name: Schedule WebdriverIO
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.3.0
      - name: Create env file
      run: |
        cat << EOF > .env
          TESTINGBOT_KEY=${{ secrets.TESTINGBOT_KEY }}
          TESTINGBOT_SECRET=${{ secrets.TESTINGBOT_SECRET }}
          COMMUNITY_USERNAME=${{ secrets.COMMUNITY_USERNAME }}
          COMMUNITY_PASSWORD=${{ secrets.COMMUNITY_PASSWORD }}
        EOF
      - name: Install
        run: npm install
      - name: Test
        run: npm run wdio-testingbot
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs